language: rust
os: linux
dist: focal
rust:
  - 1.46.0
  - stable
  - beta
  - nightly
env:
  global:
    - RUSTFLAGS='-F warnings'
    - RUST_BACKTRACE=full
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      install: cargo fmt --version || rustup component add rustfmt
      script: cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      install: cargo clippy --version || rustup component add clippy
      script: cargo clippy -- --deny warnings
    - stage: Check
      name: Expand
      install:
        - cargo fmt --version || rustup component add rustfmt
        - cargo clippy --version || rustup component add clippy
        - cargo install cargo-expand
        - rustup install nightly
      script: .ci-scripts/test-expand
    - stage: Test
      os: osx
    - stage: Test
      os: windows
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
