name: CI
on:
  push:
    branches: [ master, develop, staging, trying ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: full
jobs:
  rustfmt:
    name: Checks / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.52.0
          components: rustfmt
      - name: Run
        run: cargo fmt --all -- --check
  clippy:
    name: Checks / Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.52.0
          components: clippy
      - name: Run
        run: cargo clippy -- --deny warnings
  test:
    name: Tests / Build & Test
    needs: [ rustfmt, clippy ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: 1.52.0  # Latest
          - build: linux
            os: ubuntu-latest
            rust: 1.31.0  # MSRV
      fail-fast: true
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4
      - name: Setup (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Setup (nightly)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: CacheKey (cargo-expand)
        id: cache-key
        run: echo "::set-output name=yyyymm::$(/bin/date -u "+%Y%m")"
      - name: Cache (cargo-expand)
        id: cache-cargo-expand
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-expand
          key: ${{ runner.os }}-${{ steps.cache-key.outputs.yyyymm }}
      - name: Setup (cargo-expand)
        if: steps.cache-cargo-expand.outputs.cache-hit != 'true'
        run: cargo expand --version || cargo +nightly install cargo-expand --locked
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all
      - name: Test Expand
        run: .ci-scripts/test-expand
  success:
    name: Success
    if: ${{ success() }}
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0
